version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
  # phpmyadmin:
  #   image: phpmyadmin
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_HOST=mysql
  my-java-app:
    image: myapp:2.0
    depends_on:
      - mysql
    ports:
      - 8081:8080
    environment:
      - DB_USER=root
      - DB_NAME=mysql 
      - DB_SERVER=mysql 
      - DB_PWD=my-secret-pw
