version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=team-member-projects
      - MYSQL_USER=admin    
      - MYSQL_PASSWORD=adminpass
    volumes:
    - mysql-data:/var/lib/mysql
  # phpmyadmin:
  #   image: phpmyadmin
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_HOST=mysql
  my-java-app:
    container_name: myapp
    image: myapp:1.1
    depends_on:
      - mysql
    ports:
      - 8081:8080
    environment:
      - DB_USER=admin
      - DB_NAME=team-member-projects
      - DB_SERVER=mysql
      - DB_PWD=adminpass
volumes:
  mysql-data:
    driver: local